# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-02 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('type', models.CharField(choices=[('Sala de aula', 'sala_de_aula'), ('Sala dos Professores', 'sala_dos_professores'), ('Corredor', 'corredor')], max_length=150, verbose_name='tipo')),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'ambiente',
                'verbose_name_plural': 'ambientes',
                'ordering': ('-created_at',),
            },
        ),
    ]
