# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-02 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambiente',
            name='type',
            field=models.CharField(choices=[('sala_de_aula', 'Sala de aula'), ('sala_dos_professores', 'Sala dos Professores'), ('corredor', 'Corredor')], max_length=150, verbose_name='tipo'),
        ),
    ]
