# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-12 23:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ambientes', '0002_auto_20170802_0245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambiente',
            name='type',
        ),
    ]
