# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-27 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ambientes', '0003_remove_ambiente_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambiente',
            name='status',
        ),
    ]
